image: ubuntu:16.04
build:
    script:
    - apt-get update -qq && apt-get install -y -qq python python-wxgtk3.0 autotools-dev autoconf-archive make
    - ./bootstrap && ./configure && make
    only:
    - master
